### ISSUE TITLE
Can't find Python executable "python", you can set the PYTHON env variable.

### ISSUE THREAD

**Issue by dasheck0** [appcom-interactive/docker-nodejs#3]
I have a node application having bcrypt as dependency. Bcrypt must be compiled before it can be installed, since it relies on some libraries. Apparently it uses python for this. I get the following error:

```
> bcrypt@0.8.7 install /node/node_modules/bcrypt
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.9.27-moby
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node/node_modules/bcrypt
gyp ERR! node -v v8.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN appcom-microservice-user@1.1.2 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-06-22T12_56_29_182Z-debug.log
```

This is my Dockerfile

```
FROM appcom/nodejs:8

COPY . /node
```

**Comment by RGPaul** [comment]
You have to adjust your Dockerfile and add your dependencies:

```
# install dependencies (node_modules) and copy into /node
ADD package.json /tmp/package.json
RUN apk add --no-cache python make gcc g++ \
  && cd /tmp \
  && npm install --only=production \
  && mv /tmp/node_modules /node/node_modules \
  && apk del python make gcc g++ \
  && rm -rf /tmp/* /var/cache/apk/* /root/.npm /root/.node-gyp
```
